let data = [
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": "EAST",
      "Unnamed: 2": "MONTH OF JAN 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 1,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 25,
      "Unnamed: 3": 0,
      "Unnamed: 4": 5,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 6,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF FEB 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 2,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 12,
      "Unnamed: 3": 0,
      "Unnamed: 4": 0,
      "Unnamed: 5": 0,
      "Unnamed: 6": 3,
      "Unnamed: 7": 0,
      "Unnamed: 8": 8,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF MARCH 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 3,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 18,
      "Unnamed: 3": 0,
      "Unnamed: 4": 3,
      "Unnamed: 5": 0,
      "Unnamed: 6": 2,
      "Unnamed: 7": 0,
      "Unnamed: 8": 2,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF APRIL 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 4,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 15,
      "Unnamed: 3": 0,
      "Unnamed: 4": 5,
      "Unnamed: 5": 0,
      "Unnamed: 6": 2,
      "Unnamed: 7": 1,
      "Unnamed: 8": 11,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF MAY 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 5,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 20,
      "Unnamed: 3": 0,
      "Unnamed: 4": 7,
      "Unnamed: 5": 0,
      "Unnamed: 6": 1,
      "Unnamed: 7": 0,
      "Unnamed: 8": 11,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF JUNE 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 6,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 29,
      "Unnamed: 3": 0,
      "Unnamed: 4": 6,
      "Unnamed: 5": 0,
      "Unnamed: 6": 1,
      "Unnamed: 7": 0,
      "Unnamed: 8": 15,
      "Unnamed: 9": 6
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF JULY 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 7,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 28,
      "Unnamed: 3": 0,
      "Unnamed: 4": 7,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 2,
      "Unnamed: 9": 4
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF AUGUST 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 8,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 21,
      "Unnamed: 3": 0,
      "Unnamed: 4": 5,
      "Unnamed: 5": 0,
      "Unnamed: 6": 1,
      "Unnamed: 7": 0,
      "Unnamed: 8": 18,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF SEPTEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 8,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 21,
      "Unnamed: 3": 0,
      "Unnamed: 4": 6,
      "Unnamed: 5": 0,
      "Unnamed: 6": 1,
      "Unnamed: 7": 0,
      "Unnamed: 8": 13,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF OCTOBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 10,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 22,
      "Unnamed: 3": 0,
      "Unnamed: 4": 4,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 7,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF NOVEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 11,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 15,
      "Unnamed: 3": 0,
      "Unnamed: 4": 4,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 7,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF DECEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 12,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 24,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 4,
      "Unnamed: 9": 1
    },
    {
      "S.NO": "S.NO",
      "RANGE/DISTRICT WISE": "RANGE/DISTRICT WISE",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": "SOUTH",
      "Unnamed: 2": "MONTH OF JAN 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 1,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 11,
      "Unnamed: 3": 0,
      "Unnamed: 4": 3,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF FEB 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 2,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 8,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 8,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF MARCH 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 3,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 13,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF APRIL 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 4,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 4,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 3
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF MAY 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 5,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 11,
      "Unnamed: 3": 0,
      "Unnamed: 4": 3,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF JUNE 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 6,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 11,
      "Unnamed: 3": 0,
      "Unnamed: 4": 0,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF JULY 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 7,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 10,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF AUGUST 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 8,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 11,
      "Unnamed: 3": 0,
      "Unnamed: 4": 3,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 2,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF SEPTEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 8,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 13,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF OCTOBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 10,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 14,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF NOVEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 11,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 10,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF DECEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 12,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 16,
      "Unnamed: 3": 0,
      "Unnamed: 4": 3,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 0
    },
    {
      "S.NO": "S.NO",
      "RANGE/DISTRICT WISE": "RANGE/DISTRICT WISE",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": "WEST",
      "Unnamed: 2": "MONTH OF JAN 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 1,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 9,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF FEB 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 2,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 11,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF MARCH 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 3,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 6,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 2,
      "Unnamed: 9": 3
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF APRIL 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 4,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 8,
      "Unnamed: 3": 0,
      "Unnamed: 4": 0,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF MAY 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 5,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 13,
      "Unnamed: 3": 0,
      "Unnamed: 4": 2,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF JUNE 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 6,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 7,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF JULY 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 7,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 7,
      "Unnamed: 3": 0,
      "Unnamed: 4": 2,
      "Unnamed: 5": 0,
      "Unnamed: 6": 1,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF AUGUST 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 8,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 7,
      "Unnamed: 3": 0,
      "Unnamed: 4": 2,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 2,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF SEPTEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 8,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 10,
      "Unnamed: 3": 0,
      "Unnamed: 4": 2,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF OCTOBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 10,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 12,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 2,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF NOVEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 11,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 13,
      "Unnamed: 3": 0,
      "Unnamed: 4": 0,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF DECEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 12,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 7,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 0
    },
    {
      "S.NO": "S.NO",
      "RANGE/DISTRICT WISE": "RANGE/DISTRICT WISE",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": "CENTRAL",
      "Unnamed: 2": "MONTH OF JAN 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 1,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 8,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF FEB 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 2,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 3,
      "Unnamed: 3": 0,
      "Unnamed: 4": 2,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF MARCH 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 3,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 6,
      "Unnamed: 3": 0,
      "Unnamed: 4": 2,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF APRIL 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 4,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 5,
      "Unnamed: 3": 0,
      "Unnamed: 4": 0,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 2,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF MAY 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 5,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 11,
      "Unnamed: 3": 0,
      "Unnamed: 4": 3,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF JUNE 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 6,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 3,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 2,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF JULY 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 7,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 5,
      "Unnamed: 3": 0,
      "Unnamed: 4": 0,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF AUGUST 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 8,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 5,
      "Unnamed: 3": 0,
      "Unnamed: 4": 1,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 3,
      "Unnamed: 9": 2
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF SEPTEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 8,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 6,
      "Unnamed: 3": 0,
      "Unnamed: 4": 0,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 0,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF OCTOBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 10,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 10,
      "Unnamed: 3": 0,
      "Unnamed: 4": 4,
      "Unnamed: 5": 0,
      "Unnamed: 6": 1,
      "Unnamed: 7": 1,
      "Unnamed: 8": 1,
      "Unnamed: 9": 0
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF NOVEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 11,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 2,
      "Unnamed: 3": 0,
      "Unnamed: 4": 3,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 1
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MONTH OF DECEMBER 2023",
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null
    },
    {
      "S.NO": 12,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": "MURDER",
      "Unnamed: 3": "MURDER IN FORM OF TARGETED KILLING",
      "Unnamed: 4": "MURDER DURING ROBBERY",
      "Unnamed: 5": "SUCIDE BOMBING/ BOMB BLAST",
      "Unnamed: 6": "HIGH WAY DACOITY/ROBBERY",
      "Unnamed: 7": "BANK ROBBERY",
      "Unnamed: 8": "CAR SNATCHING",
      "Unnamed: 9": "GANG RAPE"
    },
    {
      "S.NO": null,
      "RANGE/DISTRICT WISE": null,
      "Unnamed: 2": 8,
      "Unnamed: 3": 0,
      "Unnamed: 4": 4,
      "Unnamed: 5": 0,
      "Unnamed: 6": 0,
      "Unnamed: 7": 0,
      "Unnamed: 8": 1,
      "Unnamed: 9": 0
    }
  ]